### ISSUE TITLE
Dockerfile location

### ISSUE THREAD

**Issue by rkm** [SMI/StructuredReports#2]
Is the Dockerfile available? It seems to be missing from the repo but is mentioned here: https://github.com/SMI/StructuredReports/blob/d3b4590b6f14b777fe655b693456741487d89d7b/doc/annotation_service_docker.md#run-interactive-for-testing

**Comment by howff** [comment]
Yes it's in https://github.com/SMI/CogStack-SemEHR
See https://github.com/SMI/CogStack-SemEHR/blob/main/Dockerfile.md
and https://github.com/SMI/CogStack-SemEHR/blob/main/Dockerfile
